export interface GuideCatalogEntry {
    url: string;
    title: string;
    emoji: string;
    category: string;
    desc: string;
    topics: string[];
}

export const GUIDE_CATALOG: GuideCatalogEntry[] = [
    {
        url: '/guides/pet-emergency-germany',
        title: "Emergency Vet Germany: Night & Weekend Help",
        emoji: '🚑',
        category: 'Emergency',
        desc: "Find local night and weekend veterinary services, official warning signs, call-ahead steps, and the federal GOT emergency-fee rules.",
        topics: ['emergency', 'vet-care', 'costs', 'dog', 'cat'],
    },
    {
        url: '/guides/emergency-vets-berlin',
        title: "24-Hour Emergency Vets in Berlin",
        emoji: '🏥',
        category: 'Emergency',
        desc: "Five clinics from the current Berlin Veterinary Chamber list, verified phone numbers, warning signs, GOT fees, and English call phrases.",
        topics: ['emergency', 'vet-care', 'costs', 'berlin', 'dog', 'cat'],
    },
    {
        url: '/guides/emergency-vets-munich',
        title: "24-Hour Emergency Vet Munich: LMU Guide",
        emoji: '🏥',
        category: 'Emergency',
        desc: "Official LMU dog-and-cat emergency access, current service limits, location, phone guidance and GOT fees.",
        topics: ['emergency', 'vet-care', 'costs', 'munich', 'dog', 'cat'],
    },
    {
        url: '/guides/emergency-vets-frankfurt',
        title: "Emergency Vet Frankfurt Guide",
        emoji: '🏥',
        category: 'Emergency',
        desc: "Emergency contacts, clinic details, call-ahead guidance, and what to expect from out-of-hours veterinary care in Frankfurt.",
        topics: ['emergency', 'vet-care', 'costs', 'frankfurt', 'dog', 'cat'],
    },
    {
        url: '/blog/pet-sitting-germany',
        title: "Pet Sitting in Germany (2026)",
        emoji: '🏡',
        category: 'Living',
        desc: "Finding a safe home for your little friends. Comparing platforms like Pawshake vs. Pensions vs. Community Swaps.",
        topics: ['living', 'travel', 'dog', 'cat'],
    },
    {
        url: '/blog/moving-to-germany-with-pet',
        title: "Moving to Germany With a Dog or Cat",
        emoji: '🐕',
        category: 'Moving',
        desc: "Choose the correct EU or non-EU route, then check microchip, rabies, certificate, owner-travel and breed requirements.",
        topics: ['moving', 'travel', 'legal', 'dog', 'cat'],
    },
    {
        url: '/blog/pet-friendly-apartments-germany',
        title: "Pet-Friendly Apartments in Berlin",
        emoji: '🏠',
        category: 'Living',
        desc: "Official Berlin search steps, the BGH dog-and-cat ruling, lease consent, application documents and a practical pet resume.",
        topics: ['living', 'housing', 'legal', 'berlin', 'dog', 'cat'],
    },
    {
        url: '/blog/eu-pet-passport-germany',
        title: "The EU Pet Passport Guide",
        emoji: '🛂',
        category: 'Bureaucracy',
        desc: "Why you need one, how to get it, and how much it costs. The golden ticket for travel within Europe.",
        topics: ['moving', 'travel', 'legal', 'vet-care', 'dog', 'cat'],
    },
    {
        url: '/blog/hundesteuer-dog-tax-germany',
        title: "Hundesteuer (Dog Tax) 101",
        emoji: '💶',
        category: 'Bureaucracy',
        desc: "Everything you need to know about German Dog Tax. Costs by city, how to register, and who is exempt.",
        topics: ['dog', 'legal', 'registration', 'costs'],
    },
    {
        url: '/blog/cat-registration-germany',
        title: "Cat Registration (Tasso & Finds)",
        emoji: '🐱',
        category: 'Safety',
        desc: "Germany has no dog tax for cats, but registration is vital. Learn about Tasso e.V., microchipping, and Findefix.",
        topics: ['cat', 'registration', 'safety', 'moving'],
    },
    {
        url: '/blog/public-transport-with-dogs-munich',
        title: "Dogs on Munich Public Transport",
        emoji: '🥨',
        category: 'Transport',
        desc: "Current MVV rules for dog tickets, leads, muzzles, Deutschlandticket travel and the MVV FLEX exception.",
        topics: ['dog', 'transport', 'legal', 'munich'],
    },
    {
        url: '/blog/public-transport-with-dogs-stuttgart',
        title: "Public Transport with Dogs: Stuttgart",
        emoji: '🏎️',
        category: 'Transport',
        desc: "VVS 2026 Guide: The 'Children's Ticket' rule, local Deutschlandticket bonuses, and the Zacke.",
        topics: ['dog', 'transport', 'legal', 'stuttgart'],
    },
    {
        url: '/blog/public-transport-with-dogs-berlin',
        title: "Public Transport with Dogs: Berlin",
        emoji: '🚇',
        category: 'Transport',
        desc: "The BVG survival guide. Ticket rules, muzzles, and safety tips for taking your dog on the U-Bahn and S-Bahn in the capital.",
        topics: ['dog', 'transport', 'legal', 'berlin'],
    },
    {
        url: '/blog/public-transport-with-dogs-hamburg',
        title: "Public Transport with Dogs: Hamburg",
        emoji: '🚢',
        category: 'Transport',
        desc: "HVV Guide: Why dogs travel free, taking the harbor ferries, and the relaxed leash policies of the North.",
        topics: ['dog', 'transport', 'legal', 'hamburg'],
    },
    {
        url: '/blog/public-transport-with-dogs-frankfurt',
        title: "Public Transport with Dogs: Frankfurt",
        emoji: '🚆',
        category: 'Transport',
        desc: "RMV Guide: Navigating the 'muzzle gray zone' and utilizing the free travel rules in Germany's financial hub.",
        topics: ['dog', 'transport', 'legal', 'frankfurt'],
    },
    {
        url: '/blog/german-vet-survival-kit-phrases',
        title: "German Vet Survival Kit Phrases",
        emoji: '🩺',
        category: 'Safety',
        desc: "Essential medical German for pet owners. From describing symptoms like 'Durchfall' to making emergency appointments.",
        topics: ['vet-care', 'emergency', 'language', 'dog', 'cat'],
    },
    {
        url: '/blog/pet-gps-tracker-germany',
        title: "📡 GPS Trackers for Pets in Germany",
        emoji: '📡',
        category: 'Safety',
        desc: "Tractive vs Kippy vs AirTag: real subscription costs, what works for outdoor cats, and the breakaway-collar safety rules nobody mentions.",
        topics: ['safety', 'products', 'dog', 'cat'],
    },
    {
        url: '/blog/adopting-pet-tierheim-germany',
        title: "🏠 Adopting from a Tierheim",
        emoji: '🏠',
        category: 'New Pet',
        desc: "The Schutzgebühr, the interview and home check, documents expats need, and what happens after you adopt from a German shelter.",
        topics: ['new-pet', 'adoption', 'costs', 'dog', 'cat'],
    },
    {
        url: '/blog/puppy-first-year-germany',
        title: "🐶 Puppy's First Year in Germany",
        emoji: '🐶',
        category: 'New Pet',
        desc: "Month-by-month timeline and a realistic 1,500-3,000 EUR budget: registrations, vaccinations, dog school, and the deadlines that matter.",
        topics: ['new-pet', 'dog', 'registration', 'health', 'costs'],
    },
    {
        url: '/blog/new-pet-checklist-germany',
        title: "✅ New Pet: First 30 Days Checklist",
        emoji: '✅',
        category: 'New Pet',
        desc: "Everything to register, insure, and organize in the first month with a new dog or cat in Germany, in the right order.",
        topics: ['new-pet', 'registration', 'insurance', 'vet-care', 'dog', 'cat'],
    },
    {
        url: '/blog/vet-costs-germany',
        title: "💶 Vet Costs in Germany: GOT Fees Explained",
        emoji: '💶',
        category: 'Bureaucracy',
        desc: "Understand GOT base fees, ordinary 1x-3x rates, emergency 2x-4x billing, invoice items, VAT and estimates.",
        topics: ['vet-care', 'costs', 'insurance', 'dog', 'cat'],
    },
    {
        url: '/blog/neutering-cost-germany',
        title: "✂️ Neutering & Spaying Costs",
        emoji: '✂️',
        category: 'Health',
        desc: "Realistic Kastration prices for cats and dogs, what quotes include, mandatory neutering rules for outdoor cats, and how to compare estimates.",
        topics: ['health', 'vet-care', 'costs', 'dog', 'cat'],
    },
    {
        url: '/blog/pet-vaccination-costs-germany',
        title: "💉 Vaccination Schedule & Costs",
        emoji: '💉',
        category: 'Health',
        desc: "The StIKo Vet puppy and kitten schedules, why rabies is now a travel vaccine, and what every jab costs under the GOT.",
        topics: ['health', 'vet-care', 'costs', 'travel', 'dog', 'cat'],
    },
    {
        url: '/blog/pet-insurance-germany',
        title: "Pet Insurance in Germany: Dog & Cat Guide",
        emoji: '💰',
        category: 'Bureaucracy',
        desc: "Compare dog liability, cat and dog health cover, surgery policies, exclusions, GOT reimbursement and policy limits.",
        topics: ['insurance', 'costs', 'health', 'dog', 'cat'],
    },
    {
        url: '/blog/dog-liability-insurance-germany',
        title: 'Dog Liability Insurance in Germany',
        emoji: '🛡️',
        category: 'Bureaucracy',
        desc: 'Check where Hundehaftpflicht is mandatory, what it covers, and which policy terms matter.',
        topics: ['insurance', 'dog', 'legal', 'registration', 'costs'],
    },
    {
        url: '/blog/german-dog-etiquette-rules',
        title: "German Dog Etiquette and Useful Phrases",
        emoji: '🐕',
        category: 'Living',
        desc: "How to greet dogs politely, read local leash signs, compare Berlin, Hamburg and Lower Saxony rules, and ask before entering venues.",
        topics: ['dog', 'living', 'legal', 'language'],
    },
    {
        url: '/blog/pet-medication-germany-guide',
        title: "💊 Pet Medication Guide",
        emoji: '💊',
        category: 'Health',
        desc: "Where to buy, how prescriptions work, and why you can't have antibiotics shipped. Comparing vet prices vs. online pharmacies like Medpets.",
        topics: ['health', 'vet-care', 'costs', 'dog', 'cat'],
    },
    {
        url: '/blog/best-dog-food-germany',
        title: "🐕 Best Dog Food in Germany",
        emoji: '🐕',
        category: 'Health',
        desc: "How to compare complete foods, German label terms, dry and wet formats, raw-diet risks and manufacturer quality checks.",
        topics: ['dog', 'nutrition', 'health', 'products'],
    },
    {
        url: '/blog/best-cat-food-germany',
        title: "🐈 Best Cat Food in Germany",
        emoji: '🐈',
        category: 'Health',
        desc: "How to compare complete foods, wet and dry formats, taurine needs, kitten nutrition and manufacturer quality checks.",
        topics: ['cat', 'nutrition', 'health', 'products'],
    },
    {
        url: '/english-speaking-vet-access-germany',
        title: "📊 Mapping English-Speaking Vets in Germany",
        emoji: '📊',
        category: 'Report',
        desc: "A coverage snapshot of our directory: 240+ practices mapped across 38 cities, where coverage is strongest, and the cities we are still expanding into.",
        topics: ['vet-care', 'directory', 'data', 'dog', 'cat'],
    },
    {
        url: '/blog/first-vet-visit-germany',
        title: "🩺 First Vet Visit in Germany",
        emoji: '🩺',
        category: 'Vet Care',
        desc: "What to bring, what to ask, how GOT billing and invoices work, and when pet-passport rules matter.",
        topics: ['vet-care', 'new-pet', 'costs', 'language', 'dog', 'cat'],
    },
    {
        url: '/blog/breed-restrictions-germany',
        title: "Banned Dog Breeds in Germany: Federal and State Rules",
        emoji: '⚠️',
        category: 'Bureaucracy',
        desc: "Check the federal import ban, its limited exceptions, and verified Berlin, Hamburg and Bavaria keeping rules before travelling.",
        topics: ['dog', 'legal', 'moving', 'travel', 'insurance'],
    },
    {
        url: '/blog/public-transport-with-dogs-cologne',
        title: "Dogs on Cologne Public Transport",
        emoji: '🚋',
        category: 'Transport',
        desc: "Dogs travel free on KVB and VRS services. Check short-leash, muzzle, seat, carrier and assistance-dog rules.",
        topics: ['dog', 'transport', 'legal', 'cologne'],
    },
    {
        url: '/blog/best-dog-parks-berlin',
        title: "Best Dog Parks in Berlin: Off-Leash Guide",
        emoji: '🌳',
        category: 'City Living',
        desc: "The definitive guide to off-leash dog areas in Berlin. Hundeauslaufgebiete by neighbourhood, leash rules, and more.",
        topics: ['dog', 'living', 'berlin', 'legal'],
    },
    {
        url: '/blog/cat-microchipping-germany',
        title: "Cat Microchipping in Germany 2026",
        emoji: '🐱',
        category: 'Bureaucracy',
        desc: "Germany is tightening cat microchipping and registration rules. Here is what expat cat owners need to know, and what you must do before it affects you.",
        topics: ['cat', 'registration', 'safety', 'moving', 'legal'],
    },
    {
        url: '/blog/tick-season-germany-pets',
        title: "Tick Season in Germany: Dog & Cat Safety",
        emoji: '🦟',
        category: 'Health',
        desc: "When ticks are active, how to check and remove them safely, species-specific prevention and urgent warning signs.",
        topics: ['health', 'safety', 'vet-care', 'dog', 'cat'],
    },
    {
        url: '/blog/emergency-vet-hamburg-english',
        title: "24-Hour Emergency Vet Hamburg: What to Call",
        emoji: '🏥',
        category: 'Emergency',
        desc: "Use Hamburg’s rotating veterinary duty service, current call number, published hours, warning signs, and GOT fee rules.",
        topics: ['emergency', 'vet-care', 'costs', 'hamburg', 'dog', 'cat'],
    },
];
